-- ============================================================
-- FINVEDA USER FIX SCRIPT
-- This script fixes:
-- 1. admin@finveda.com: role '1' (integer) -> 'super_admin' (enum name)
-- 2. 22222222-xxxx users: invalid 82-char BCrypt hashes -> valid hash for Admin@123
-- 3. Duplicate super_admin@finveda.com entries (keep the working one)
-- Password: Admin@123 -> hash generated by the API: $2a$11$JB1QPJa2RzwxqWOWY2GwE.HV.ivtQ8RH45f6MTyAr4POcGlNlLNma
-- ============================================================

-- Fix 1: admin@finveda.com - change role from '1' to 'super_admin'
UPDATE users 
SET role = 'super_admin'
WHERE email = 'admin@finveda.com' AND role = '1';

-- Fix 2: Update all 22222222-xxxx users with valid BCrypt hash for Admin@123
UPDATE users 
SET password_hash = '$2a$11$JB1QPJa2RzwxqWOWY2GwE.HV.ivtQ8RH45f6MTyAr4POcGlNlLNma'
WHERE id IN (
    '22222222-2222-2222-2222-222222222221',
    '22222222-2222-2222-2222-222222222222',
    '22222222-2222-2222-2222-222222222223',
    '22222222-2222-2222-2222-222222222224',
    '22222222-2222-2222-2222-222222222225',
    '22222222-2222-2222-2222-222222222226',
    '22222222-2222-2222-2222-222222222227',
    '22222222-2222-2222-2222-222222222228',
    '22222222-2222-2222-2222-222222222229'
);

-- Fix 3: Clean up the temp user created for hash generation
DELETE FROM users WHERE email = 'temp_hash_test@finveda.com';

-- Fix 4: Update duplicate super_admin@finveda.com (22222222... version) to avoid conflict
-- The e3ea4fa1 version has a valid hash; the 22222222...221 version is now also valid with Admin@123
-- Both can coexist (different IDs), so no action needed unless you want to remove one

-- Verify: Show all users after fix
SELECT id, email, LENGTH(password_hash) as hash_len, role, is_active 
FROM users 
ORDER BY email;
