services:
  - type: web
    name: fintech-backend
    env: docker
    dockerfilePath: ./Dockerfile
    branch: main
    region: singapore
    plan: free
    healthCheckPath: /swagger
    envVars:
      - key: ConnectionStrings__DefaultConnection
        value: Host=ep-wandering-mud-ada1ui28-pooler.c-2.us-east-1.aws.neon.tech;Database=neondb;Username=neondb_owner;Password=npg_V0lQJDLiq9Eb;SSL Mode=Require;Trust Server Certificate=true;Pooling=true;Maximum Pool Size=5;Connection Idle Lifetime=30;
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: Jwt__Key
        value: VettriFinance2026SecretKeyForJWT123456789012
      - key: Jwt__Issuer
        value: VettriFinance
      - key: Jwt__Audience
        value: VettriFinanceAPI
      - key: AllowedOrigins__0
        value: https://fintaech-front-end.vercel.app
      - key: ASPNETCORE_URLS
        value: http://+:8080
