services:
  - type: web
    name: fintech-backend
    env: docker
    dockerfilePath: ./Dockerfile
    branch: main
    region: singapore
    plan: free
    healthCheckPath: /swagger
    envVars:
      - key: ConnectionStrings__DefaultConnection
        value: Host=dpg-d9chkoe7r5hc73bdlmtg-a.oregon-postgres.render.com;Database=fintech_db_4tu1;Username=fintech_db_4tu1_user;Password=KDhmX5sVnKjzObdJK4F30u3zuloVtA15;SSL Mode=Require;Trust Server Certificate=true;
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: Jwt__Key
        value: VettriFinance2026SecretKeyForJWT123456789012
      - key: Jwt__Issuer
        value: VettriFinance
      - key: Jwt__Audience
        value: VettriFinanceAPI
      - key: AllowedOrigins__0
        value: https://fintaech-front-end.vercel.app
      - key: ASPNETCORE_URLS
        value: http://+:8080
