// <auto-generated />
using System;
using Fintech.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Fintech.Migrations
{
    [DbContext(typeof(FinVedaDbContext))]
    [Migration("20260616185635_AddCustomerCodeColumn")]
    partial class AddCustomerCodeColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Fintech.Core.Domain.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccountCode")
                        .HasColumnType("text")
                        .HasColumnName("account_code");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_accounts");

                    b.HasIndex("AccountCode")
                        .IsUnique()
                        .HasDatabaseName("ix_accounts_account_code");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("Fintech.Core.Domain.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<string>("AfterVal")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("after_val");

                    b.Property<string>("AuditLogCode")
                        .HasColumnType("text")
                        .HasColumnName("audit_log_code");

                    b.Property<string>("BeforeVal")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("before_val");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<string>("RecordId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("record_id");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("table_name");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.HasIndex("AuditLogCode")
                        .IsUnique()
                        .HasDatabaseName("ix_audit_logs_audit_log_code");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("Fintech.Core.Domain.Branch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BranchCode")
                        .HasColumnType("text")
                        .HasColumnName("branch_code");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("SettingsJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("settings_json");

                    b.HasKey("Id")
                        .HasName("pk_branches");

                    b.HasIndex("BranchCode")
                        .IsUnique()
                        .HasDatabaseName("ix_branches_branch_code");

                    b.ToTable("branches", (string)null);
                });

            modelBuilder.Entity("Fintech.Core.Domain.CapitalAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint")
                        .HasColumnName("amount");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<string>("CapitalAccountCode")
                        .HasColumnType("text")
                        .HasColumnName("capital_account_code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("PartnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("partner_id");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("transaction_type");

                    b.HasKey("Id")
                        .HasName("pk_capital_accounts");

                    b.HasIndex("CapitalAccountCode")
                        .IsUnique()
                        .HasDatabaseName("ix_capital_accounts_capital_account_code");

                    b.HasIndex("PartnerId")
                        .HasDatabaseName("ix_capital_accounts_partner_id");

                    b.ToTable("capital_accounts", (string)null);
                });

            modelBuilder.Entity("Fintech.Core.Domain.CodeSequence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<string>("CodePrefix")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("code_prefix");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_name");

                    b.Property<int>("NextSequenceNumber")
                        .HasColumnType("integer")
                        .HasColumnName("next_sequence_number");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_code_sequences");

                    b.HasIndex("EntityName", "BranchId")
                        .IsUnique()
                        .HasDatabaseName("ix_code_sequences_entity_name_branch_id");

                    b.ToTable("code_sequences", (string)null);
                });

            modelBuilder.Entity("Fintech.Core.Domain.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Aadhaar_Encrypted")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("aadhaar_encrypted");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<string>("CustomerCode")
                        .HasColumnType("text")
                        .HasColumnName("customer_code");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PAN_Encrypted")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pan_encrypted");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.HasKey("Id")
                        .HasName("pk_customers");

                    b.HasIndex("CustomerCode")
                        .IsUnique()
                        .HasDatabaseName("ix_customers_customer_code");

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("Fintech.Core.Domain.DayEnd", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<string>("DayEndCode")
                        .HasColumnType("text")
                        .HasColumnName("day_end_code");

                    b.Property<long>("Discrepancy")
                        .HasColumnType("bigint")
                        .HasColumnName("discrepancy");

                    b.Property<bool>("DiscrepancyResolved")
                        .HasColumnType("boolean")
                        .HasColumnName("discrepancy_resolved");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_closed");

                    b.Property<int>("JournalsLocked")
                        .HasColumnType("integer")
                        .HasColumnName("journals_locked");

                    b.Property<long>("TotalCollected")
                        .HasColumnType("bigint")
                        .HasColumnName("total_collected");

                    b.HasKey("Id")
                        .HasName("pk_day_ends");

                    b.HasIndex("DayEndCode")
                        .IsUnique()
                        .HasDatabaseName("ix_day_ends_day_end_code");

                    b.ToTable("day_ends", (string)null);
                });

            modelBuilder.Entity("Fintech.Core.Domain.Installment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint")
                        .HasColumnName("amount");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_date");

                    b.Property<string>("InstallmentCode")
                        .HasColumnType("text")
                        .HasColumnName("installment_code");

                    b.Property<Guid>("LoanCaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("loan_case_id");

                    b.Property<int>("No")
                        .HasColumnType("integer")
                        .HasColumnName("installment_no");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_installments");

                    b.HasIndex("InstallmentCode")
                        .IsUnique()
                        .HasDatabaseName("ix_installments_installment_code");

                    b.HasIndex("LoanCaseId")
                        .HasDatabaseName("ix_installments_loan_case_id");

                    b.ToTable("installments", (string)null);
                });

            modelBuilder.Entity("Fintech.Core.Domain.JournalEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("entry_date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsManual")
                        .HasColumnType("boolean")
                        .HasColumnName("is_manual");

                    b.Property<bool>("IsPosted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_posted");

                    b.Property<string>("JournalEntryCode")
                        .HasColumnType("text")
                        .HasColumnName("journal_entry_code");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("public_id");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reference");

                    b.HasKey("Id")
                        .HasName("pk_journal_entries");

                    b.HasIndex("JournalEntryCode")
                        .IsUnique()
                        .HasDatabaseName("ix_journal_entries_journal_entry_code");

                    b.ToTable("journal_entries", (string)null);
                });

            modelBuilder.Entity("Fintech.Core.Domain.JournalLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("account_name");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint")
                        .HasColumnName("amount");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<Guid>("JournalEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("journal_entry_id");

                    b.Property<string>("JournalLineCode")
                        .HasColumnType("text")
                        .HasColumnName("journal_line_code");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entry_type");

                    b.HasKey("Id")
                        .HasName("pk_journal_lines");

                    b.HasIndex("JournalEntryId")
                        .HasDatabaseName("ix_journal_lines_journal_entry_id");

                    b.HasIndex("JournalLineCode")
                        .IsUnique()
                        .HasDatabaseName("ix_journal_lines_journal_line_code");

                    b.ToTable("journal_lines", (string)null);
                });

            modelBuilder.Entity("Fintech.Core.Domain.LoanCase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<long>("InterestAmount")
                        .HasColumnType("bigint")
                        .HasColumnName("interest_amount");

                    b.Property<string>("LoanCode")
                        .HasColumnType("text")
                        .HasColumnName("loan_code");

                    b.Property<long>("Principal")
                        .HasColumnType("bigint")
                        .HasColumnName("finance_amount");

                    b.Property<long>("ProcessingFees")
                        .HasColumnType("bigint")
                        .HasColumnName("file_charges_amount");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<long>("TotalReceivable")
                        .HasColumnType("bigint")
                        .HasColumnName("total_receivable");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_loan_cases");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_loan_cases_customer_id");

                    b.HasIndex("LoanCode")
                        .IsUnique()
                        .HasDatabaseName("ix_loan_cases_loan_code");

                    b.ToTable("loan_cases", (string)null);
                });

            modelBuilder.Entity("Fintech.Core.Domain.LoanProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<int>("DefaultTenureMonths")
                        .HasColumnType("integer")
                        .HasColumnName("default_tenure_months");

                    b.Property<double>("InterestRate")
                        .HasColumnType("double precision")
                        .HasColumnName("interest_rate");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("RepaymentFrequency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("repayment_frequency");

                    b.HasKey("Id")
                        .HasName("pk_loan_products");

                    b.ToTable("loan_products", (string)null);
                });

            modelBuilder.Entity("Fintech.Core.Domain.Partner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<double>("EquityPct")
                        .HasColumnType("double precision")
                        .HasColumnName("equity_pct");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("PartnerCode")
                        .HasColumnType("text")
                        .HasColumnName("partner_code");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_partners");

                    b.HasIndex("PartnerCode")
                        .IsUnique()
                        .HasDatabaseName("ix_partners_partner_code");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_partners_user_id");

                    b.ToTable("partners", (string)null);
                });

            modelBuilder.Entity("Fintech.Core.Domain.ProfitDistribution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<Guid>("PartnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("partner_id");

                    b.Property<long>("PayoutAmount")
                        .HasColumnType("bigint")
                        .HasColumnName("payout_amount");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("period");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("ProfitDistributionCode")
                        .HasColumnType("text")
                        .HasColumnName("profit_distribution_code");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_profit_distributions");

                    b.HasIndex("PartnerId")
                        .HasDatabaseName("ix_profit_distributions_partner_id");

                    b.HasIndex("ProfitDistributionCode")
                        .IsUnique()
                        .HasDatabaseName("ix_profit_distributions_profit_distribution_code");

                    b.ToTable("profit_distributions", (string)null);
                });

            modelBuilder.Entity("Fintech.Core.Domain.Receipt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("AmountPaid")
                        .HasColumnType("bigint")
                        .HasColumnName("amount_paid");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("captured_at");

                    b.Property<Guid>("InstallmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("installment_id");

                    b.Property<Guid>("LoanCaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("loan_case_id");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mode");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("public_id");

                    b.Property<string>("ReceiptCode")
                        .HasColumnType("text")
                        .HasColumnName("receipt_code");

                    b.Property<string>("UTRRef")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("utr_ref");

                    b.HasKey("Id")
                        .HasName("pk_receipts");

                    b.HasIndex("InstallmentId")
                        .HasDatabaseName("ix_receipts_installment_id");

                    b.HasIndex("LoanCaseId")
                        .HasDatabaseName("ix_receipts_loan_case_id");

                    b.HasIndex("ReceiptCode")
                        .IsUnique()
                        .HasDatabaseName("ix_receipts_receipt_code");

                    b.ToTable("receipts", (string)null);
                });

            modelBuilder.Entity("Fintech.Core.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("refresh_token");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<bool>("TotpEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("totp_enabled");

                    b.Property<string>("UserCode")
                        .HasColumnType("text")
                        .HasColumnName("user_code");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("UserCode")
                        .IsUnique()
                        .HasDatabaseName("ix_users_user_code");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Fintech.Core.Domain.CapitalAccount", b =>
                {
                    b.HasOne("Fintech.Core.Domain.Partner", "Partner")
                        .WithMany("CapitalAccounts")
                        .HasForeignKey("PartnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_capital_accounts_partners_partner_id");

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("Fintech.Core.Domain.Installment", b =>
                {
                    b.HasOne("Fintech.Core.Domain.LoanCase", "LoanCase")
                        .WithMany("Installments")
                        .HasForeignKey("LoanCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_installments_loan_cases_loan_case_id");

                    b.Navigation("LoanCase");
                });

            modelBuilder.Entity("Fintech.Core.Domain.JournalLine", b =>
                {
                    b.HasOne("Fintech.Core.Domain.JournalEntry", "JournalEntry")
                        .WithMany("Lines")
                        .HasForeignKey("JournalEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_journal_lines_journal_entries_journal_entry_id");

                    b.Navigation("JournalEntry");
                });

            modelBuilder.Entity("Fintech.Core.Domain.LoanCase", b =>
                {
                    b.HasOne("Fintech.Core.Domain.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_loan_cases_customers_customer_id");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Fintech.Core.Domain.Partner", b =>
                {
                    b.HasOne("Fintech.Core.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_partners_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Fintech.Core.Domain.ProfitDistribution", b =>
                {
                    b.HasOne("Fintech.Core.Domain.Partner", "Partner")
                        .WithMany()
                        .HasForeignKey("PartnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_profit_distributions_partners_partner_id");

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("Fintech.Core.Domain.Receipt", b =>
                {
                    b.HasOne("Fintech.Core.Domain.Installment", "Installment")
                        .WithMany()
                        .HasForeignKey("InstallmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_receipts_installments_installment_id");

                    b.HasOne("Fintech.Core.Domain.LoanCase", "LoanCase")
                        .WithMany()
                        .HasForeignKey("LoanCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_receipts_loan_cases_loan_case_id");

                    b.Navigation("Installment");

                    b.Navigation("LoanCase");
                });

            modelBuilder.Entity("Fintech.Core.Domain.JournalEntry", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Fintech.Core.Domain.LoanCase", b =>
                {
                    b.Navigation("Installments");
                });

            modelBuilder.Entity("Fintech.Core.Domain.Partner", b =>
                {
                    b.Navigation("CapitalAccounts");
                });
#pragma warning restore 612, 618
        }
    }
}
