// <auto-generated />
using System;
using Fintech.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Fintech.Migrations
{
    [DbContext(typeof(FinVedaDbContext))]
    [Migration("20260621085215_Phase6Integration")]
    partial class Phase6Integration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Fintech.Core.Domain.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccountCode")
                        .HasColumnType("text")
                        .HasColumnName("account_code");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_accounts");

                    b.HasIndex("AccountCode")
                        .IsUnique()
                        .HasDatabaseName("ix_accounts_account_code");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("Fintech.Core.Domain.AccountMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<string>("CapitalAccountCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("capital_account_code");

                    b.Property<Guid>("CapitalAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("capital_account_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("GLAccountCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("gl_account_code");

                    b.Property<Guid>("GLAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("gl_account_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_account_mappings");

                    b.HasIndex("GLAccountCode")
                        .HasDatabaseName("ix_account_mappings_gl_account_code");

                    b.HasIndex("BranchId", "CapitalAccountCode")
                        .IsUnique()
                        .HasDatabaseName("ix_account_mappings_branch_id_capital_account_code");

                    b.ToTable("account_mappings", (string)null);
                });

            modelBuilder.Entity("Fintech.Core.Domain.AccountingPeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<string>("ClosedBy")
                        .HasColumnType("text")
                        .HasColumnName("closed_by");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("PeriodCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("period_code");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_accounting_periods");

                    b.HasIndex("PeriodCode")
                        .IsUnique()
                        .HasDatabaseName("ix_accounting_periods_period_code");

                    b.HasIndex("BranchId", "Status")
                        .HasDatabaseName("ix_accounting_periods_branch_id_status");

                    b.ToTable("accounting_periods", (string)null);
                });

            modelBuilder.Entity("Fintech.Core.Domain.AccrualEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AccrualDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accrual_date");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<Guid>("JournalEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("journal_entry_id");

                    b.Property<Guid?>("LoanId")
                        .HasColumnType("uuid")
                        .HasColumnName("loan_id");

                    b.Property<Guid>("PeriodId")
                        .HasColumnType("uuid")
                        .HasColumnName("period_id");

                    b.Property<Guid?>("ReversalJournalEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("reversal_journal_entry_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_accrual_entries");

                    b.HasIndex("JournalEntryId")
                        .HasDatabaseName("ix_accrual_entries_journal_entry_id");

                    b.HasIndex("LoanId")
                        .HasDatabaseName("ix_accrual_entries_loan_id");

                    b.HasIndex("PeriodId")
                        .HasDatabaseName("ix_accrual_entries_period_id");

                    b.HasIndex("ReversalJournalEntryId")
                        .HasDatabaseName("ix_accrual_entries_reversal_journal_entry_id");

                    b.HasIndex("Type")
                        .HasDatabaseName("ix_accrual_entries_type");

                    b.ToTable("accrual_entries", (string)null);
                });

            modelBuilder.Entity("Fintech.Core.Domain.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<string>("AfterVal")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("after_val");

                    b.Property<string>("AuditLogCode")
                        .HasColumnType("text")
                        .HasColumnName("audit_log_code");

                    b.Property<string>("BeforeVal")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("before_val");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<string>("RecordId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("record_id");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("table_name");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.HasIndex("AuditLogCode")
                        .IsUnique()
                        .HasDatabaseName("ix_audit_logs_audit_log_code");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("Fintech.Core.Domain.Branch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BranchCode")
                        .HasColumnType("text")
                        .HasColumnName("branch_code");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("SettingsJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("settings_json");

                    b.HasKey("Id")
                        .HasName("pk_branches");

                    b.HasIndex("BranchCode")
                        .IsUnique()
                        .HasDatabaseName("ix_branches_branch_code");

                    b.ToTable("branches", (string)null);
                });

            modelBuilder.Entity("Fintech.Core.Domain.CapitalAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CapitalAccountCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("capital_account_code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("currency");

                    b.Property<long>("CurrentBalance")
                        .HasColumnType("bigint")
                        .HasColumnName("current_balance");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_at");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modified_by");

                    b.Property<long>("OpeningBalance")
                        .HasColumnType("bigint")
                        .HasColumnName("opening_balance");

                    b.Property<decimal>("OwnershipPercentage")
                        .HasColumnType("numeric")
                        .HasColumnName("ownership_percentage");

                    b.Property<Guid>("PartnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("partner_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_capital_accounts");

                    b.HasIndex("CapitalAccountCode")
                        .IsUnique()
                        .HasDatabaseName("ix_capital_accounts_capital_account_code");

                    b.HasIndex("PartnerId")
                        .HasDatabaseName("ix_capital_accounts_partner_id");

                    b.ToTable("capital_accounts", (string)null);
                });

            modelBuilder.Entity("Fintech.Core.Domain.CapitalAccountHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("Balance")
                        .HasColumnType("bigint")
                        .HasColumnName("balance");

                    b.Property<Guid>("CapitalAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("capital_account_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_date");

                    b.Property<decimal>("OwnershipPercentage")
                        .HasColumnType("numeric")
                        .HasColumnName("ownership_percentage");

                    b.Property<long>("TotalCapitalAtDate")
                        .HasColumnType("bigint")
                        .HasColumnName("total_capital_at_date");

                    b.HasKey("Id")
                        .HasName("pk_capital_account_histories");

                    b.HasIndex("CapitalAccountId", "EffectiveDate")
                        .IsUnique()
                        .HasDatabaseName("ix_capital_account_histories_capital_account_id_effective_date");

                    b.ToTable("capital_account_histories", (string)null);
                });

            modelBuilder.Entity("Fintech.Core.Domain.CapitalTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint")
                        .HasColumnName("amount");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by");

                    b.Property<Guid>("CapitalAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("capital_account_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_at");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("ReferenceNumber")
                        .HasColumnType("text")
                        .HasColumnName("reference_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("TransactionCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("transaction_code");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("transaction_date");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("transaction_type");

                    b.HasKey("Id")
                        .HasName("pk_capital_transactions");

                    b.HasIndex("ApprovedBy")
                        .HasDatabaseName("ix_capital_transactions_approved_by");

                    b.HasIndex("CapitalAccountId")
                        .HasDatabaseName("ix_capital_transactions_capital_account_id");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_capital_transactions_created_by");

                    b.HasIndex("TransactionCode")
                        .IsUnique()
                        .HasDatabaseName("ix_capital_transactions_transaction_code");

                    b.ToTable("capital_transactions", (string)null);
                });

            modelBuilder.Entity("Fintech.Core.Domain.CodeSequence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<string>("CodePrefix")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("code_prefix");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_name");

                    b.Property<int>("NextSequenceNumber")
                        .HasColumnType("integer")
                        .HasColumnName("next_sequence_number");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_code_sequences");

                    b.HasIndex("EntityName", "BranchId")
                        .IsUnique()
                        .HasDatabaseName("ix_code_sequences_entity_name_branch_id");

                    b.ToTable("code_sequences", (string)null);
                });

            modelBuilder.Entity("Fintech.Core.Domain.CollectionRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint")
                        .HasColumnName("amount");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<Guid?>("ApprovedById")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by_id");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<Guid>("InstallmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("installment_id");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ip_address");

                    b.Property<Guid>("LoanCaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("loan_case_id");

                    b.Property<long>("NewDueAmount")
                        .HasColumnType("bigint")
                        .HasColumnName("new_due_amount");

                    b.Property<string>("PaymentMode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payment_mode");

                    b.Property<long>("PreviousDueAmount")
                        .HasColumnType("bigint")
                        .HasColumnName("previous_due_amount");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("remarks");

                    b.Property<string>("RequestNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("request_number");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at");

                    b.Property<Guid>("RequestedById")
                        .HasColumnType("uuid")
                        .HasColumnName("requested_by_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("UtrRef")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("utr_ref");

                    b.HasKey("Id")
                        .HasName("pk_collection_requests");

                    b.HasIndex("ApprovedById")
                        .HasDatabaseName("ix_collection_requests_approved_by_id");

                    b.HasIndex("InstallmentId")
                        .HasDatabaseName("ix_collection_requests_installment_id");

                    b.HasIndex("LoanCaseId")
                        .HasDatabaseName("ix_collection_requests_loan_case_id");

                    b.HasIndex("RequestNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_collection_requests_request_number");

                    b.HasIndex("RequestedById")
                        .HasDatabaseName("ix_collection_requests_requested_by_id");

                    b.ToTable("collection_requests", (string)null);
                });

            modelBuilder.Entity("Fintech.Core.Domain.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Aadhaar_Encrypted")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("aadhaar_encrypted");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PAN_Encrypted")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pan_encrypted");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.HasKey("Id")
                        .HasName("pk_customers");

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("Fintech.Core.Domain.DayEnd", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<string>("DayEndCode")
                        .HasColumnType("text")
                        .HasColumnName("day_end_code");

                    b.Property<long>("Discrepancy")
                        .HasColumnType("bigint")
                        .HasColumnName("discrepancy");

                    b.Property<bool>("DiscrepancyResolved")
                        .HasColumnType("boolean")
                        .HasColumnName("discrepancy_resolved");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_closed");

                    b.Property<int>("JournalsLocked")
                        .HasColumnType("integer")
                        .HasColumnName("journals_locked");

                    b.Property<long>("TotalCollected")
                        .HasColumnType("bigint")
                        .HasColumnName("total_collected");

                    b.HasKey("Id")
                        .HasName("pk_day_ends");

                    b.HasIndex("DayEndCode")
                        .IsUnique()
                        .HasDatabaseName("ix_day_ends_day_end_code");

                    b.ToTable("day_ends", (string)null);
                });

            modelBuilder.Entity("Fintech.Core.Domain.Installment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint")
                        .HasColumnName("amount");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_date");

                    b.Property<string>("InstallmentCode")
                        .HasColumnType("text")
                        .HasColumnName("installment_code");

                    b.Property<Guid>("LoanCaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("loan_case_id");

                    b.Property<int>("No")
                        .HasColumnType("integer")
                        .HasColumnName("installment_no");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_installments");

                    b.HasIndex("InstallmentCode")
                        .IsUnique()
                        .HasDatabaseName("ix_installments_installment_code");

                    b.HasIndex("LoanCaseId")
                        .HasDatabaseName("ix_installments_loan_case_id");

                    b.ToTable("installments", (string)null);
                });

            modelBuilder.Entity("Fintech.Core.Domain.JournalEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<Guid?>("CapitalTransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("capital_transaction_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("entry_date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsManual")
                        .HasColumnType("boolean")
                        .HasColumnName("is_manual");

                    b.Property<bool>("IsPosted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_posted");

                    b.Property<string>("JournalEntryCode")
                        .HasColumnType("text")
                        .HasColumnName("journal_entry_code");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("public_id");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reference");

                    b.Property<Guid?>("ReversalOfEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("reversal_of_entry_id");

                    b.HasKey("Id")
                        .HasName("pk_journal_entries");

                    b.HasIndex("CapitalTransactionId")
                        .HasDatabaseName("ix_journal_entries_capital_transaction_id");

                    b.HasIndex("JournalEntryCode")
                        .IsUnique()
                        .HasDatabaseName("ix_journal_entries_journal_entry_code");

                    b.ToTable("journal_entries", (string)null);
                });

            modelBuilder.Entity("Fintech.Core.Domain.JournalLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccountCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("account_code");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("account_name");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint")
                        .HasColumnName("amount");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<Guid>("JournalEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("journal_entry_id");

                    b.Property<string>("JournalLineCode")
                        .HasColumnType("text")
                        .HasColumnName("journal_line_code");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entry_type");

                    b.HasKey("Id")
                        .HasName("pk_journal_lines");

                    b.HasIndex("JournalEntryId")
                        .HasDatabaseName("ix_journal_lines_journal_entry_id");

                    b.HasIndex("JournalLineCode")
                        .IsUnique()
                        .HasDatabaseName("ix_journal_lines_journal_line_code");

                    b.ToTable("journal_lines", (string)null);
                });

            modelBuilder.Entity("Fintech.Core.Domain.LedgerBalance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("account_name");

                    b.Property<long>("Balance")
                        .HasColumnType("bigint")
                        .HasColumnName("balance");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<string>("GLAccountCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("gl_account_code");

                    b.Property<Guid>("GLAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("gl_account_id");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated");

                    b.Property<long>("TotalCredits")
                        .HasColumnType("bigint")
                        .HasColumnName("total_credits");

                    b.Property<long>("TotalDebits")
                        .HasColumnType("bigint")
                        .HasColumnName("total_debits");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_ledger_balances");

                    b.HasIndex("BranchId", "GLAccountCode")
                        .IsUnique()
                        .HasDatabaseName("ix_ledger_balances_branch_id_gl_account_code");

                    b.ToTable("ledger_balances", (string)null);
                });

            modelBuilder.Entity("Fintech.Core.Domain.LedgerHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("Balance")
                        .HasColumnType("bigint")
                        .HasColumnName("balance");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<long>("Credits")
                        .HasColumnType("bigint")
                        .HasColumnName("credits");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<long>("Debits")
                        .HasColumnType("bigint")
                        .HasColumnName("debits");

                    b.Property<string>("GLAccountCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("gl_account_code");

                    b.Property<Guid>("GLAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("gl_account_id");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.HasKey("Id")
                        .HasName("pk_ledger_histories");

                    b.HasIndex("BranchId", "GLAccountCode", "Date")
                        .HasDatabaseName("ix_ledger_histories_branch_id_gl_account_code_date");

                    b.ToTable("ledger_histories", (string)null);
                });

            modelBuilder.Entity("Fintech.Core.Domain.LoanCase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<long>("InterestAmount")
                        .HasColumnType("bigint")
                        .HasColumnName("interest_amount");

                    b.Property<string>("LoanCode")
                        .HasColumnType("text")
                        .HasColumnName("loan_code");

                    b.Property<long>("Principal")
                        .HasColumnType("bigint")
                        .HasColumnName("finance_amount");

                    b.Property<long>("ProcessingFees")
                        .HasColumnType("bigint")
                        .HasColumnName("file_charges_amount");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<long>("TotalReceivable")
                        .HasColumnType("bigint")
                        .HasColumnName("total_receivable");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_loan_cases");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_loan_cases_customer_id");

                    b.HasIndex("LoanCode")
                        .IsUnique()
                        .HasDatabaseName("ix_loan_cases_loan_code");

                    b.ToTable("loan_cases", (string)null);
                });

            modelBuilder.Entity("Fintech.Core.Domain.LoanProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<int>("DefaultTenureMonths")
                        .HasColumnType("integer")
                        .HasColumnName("default_tenure_months");

                    b.Property<double>("InterestRate")
                        .HasColumnType("double precision")
                        .HasColumnName("interest_rate");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("RepaymentFrequency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("repayment_frequency");

                    b.HasKey("Id")
                        .HasName("pk_loan_products");

                    b.ToTable("loan_products", (string)null);
                });

            modelBuilder.Entity("Fintech.Core.Domain.Partner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<double>("EquityPct")
                        .HasColumnType("double precision")
                        .HasColumnName("equity_pct");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("PartnerCode")
                        .HasColumnType("text")
                        .HasColumnName("partner_code");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_partners");

                    b.HasIndex("PartnerCode")
                        .IsUnique()
                        .HasDatabaseName("ix_partners_partner_code");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_partners_user_id");

                    b.ToTable("partners", (string)null);
                });

            modelBuilder.Entity("Fintech.Core.Domain.PeriodReversal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("DeletedAccruals")
                        .HasColumnType("integer")
                        .HasColumnName("deleted_accruals");

                    b.Property<int?>("DeletedJournalEntries")
                        .HasColumnType("integer")
                        .HasColumnName("deleted_journal_entries");

                    b.Property<int?>("DeletedProvisions")
                        .HasColumnType("integer")
                        .HasColumnName("deleted_provisions");

                    b.Property<Guid>("PeriodId")
                        .HasColumnType("uuid")
                        .HasColumnName("period_id");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<DateTime>("ReversedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reversed_at");

                    b.Property<string>("ReversedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reversed_by");

                    b.HasKey("Id")
                        .HasName("pk_period_reversals");

                    b.HasIndex("PeriodId")
                        .HasDatabaseName("ix_period_reversals_period_id");

                    b.ToTable("period_reversals", (string)null);
                });

            modelBuilder.Entity("Fintech.Core.Domain.ProfitDistribution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<Guid>("PartnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("partner_id");

                    b.Property<long>("PayoutAmount")
                        .HasColumnType("bigint")
                        .HasColumnName("payout_amount");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("period");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("ProfitDistributionCode")
                        .HasColumnType("text")
                        .HasColumnName("profit_distribution_code");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_profit_distributions");

                    b.HasIndex("PartnerId")
                        .HasDatabaseName("ix_profit_distributions_partner_id");

                    b.HasIndex("ProfitDistributionCode")
                        .IsUnique()
                        .HasDatabaseName("ix_profit_distributions_profit_distribution_code");

                    b.ToTable("profit_distributions", (string)null);
                });

            modelBuilder.Entity("Fintech.Core.Domain.ProvisionEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint")
                        .HasColumnName("amount");

                    b.Property<string>("CalculationMethod")
                        .HasColumnType("text")
                        .HasColumnName("calculation_method");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<Guid>("JournalEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("journal_entry_id");

                    b.Property<Guid?>("LoanId")
                        .HasColumnType("uuid")
                        .HasColumnName("loan_id");

                    b.Property<Guid>("PeriodId")
                        .HasColumnType("uuid")
                        .HasColumnName("period_id");

                    b.Property<long>("PreviousAmount")
                        .HasColumnType("bigint")
                        .HasColumnName("previous_amount");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_provision_entries");

                    b.HasIndex("JournalEntryId")
                        .HasDatabaseName("ix_provision_entries_journal_entry_id");

                    b.HasIndex("LoanId")
                        .HasDatabaseName("ix_provision_entries_loan_id");

                    b.HasIndex("PeriodId")
                        .HasDatabaseName("ix_provision_entries_period_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_provision_entries_status");

                    b.ToTable("provision_entries", (string)null);
                });

            modelBuilder.Entity("Fintech.Core.Domain.Receipt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("AmountPaid")
                        .HasColumnType("bigint")
                        .HasColumnName("amount_paid");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("captured_at");

                    b.Property<Guid>("InstallmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("installment_id");

                    b.Property<Guid>("LoanCaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("loan_case_id");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mode");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("public_id");

                    b.Property<string>("ReceiptCode")
                        .HasColumnType("text")
                        .HasColumnName("receipt_code");

                    b.Property<string>("UTRRef")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("utr_ref");

                    b.HasKey("Id")
                        .HasName("pk_receipts");

                    b.HasIndex("InstallmentId")
                        .HasDatabaseName("ix_receipts_installment_id");

                    b.HasIndex("LoanCaseId")
                        .HasDatabaseName("ix_receipts_loan_case_id");

                    b.HasIndex("ReceiptCode")
                        .IsUnique()
                        .HasDatabaseName("ix_receipts_receipt_code");

                    b.ToTable("receipts", (string)null);
                });

            modelBuilder.Entity("Fintech.Core.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("refresh_token");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<bool>("TotpEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("totp_enabled");

                    b.Property<string>("UserCode")
                        .HasColumnType("text")
                        .HasColumnName("user_code");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("UserCode")
                        .IsUnique()
                        .HasDatabaseName("ix_users_user_code");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Fintech.Core.Domain.AccrualEntry", b =>
                {
                    b.HasOne("Fintech.Core.Domain.JournalEntry", "JournalEntry")
                        .WithMany()
                        .HasForeignKey("JournalEntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_accrual_entries_journal_entries_journal_entry_id");

                    b.HasOne("Fintech.Core.Domain.LoanCase", "Loan")
                        .WithMany()
                        .HasForeignKey("LoanId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_accrual_entries_loan_cases_loan_id");

                    b.HasOne("Fintech.Core.Domain.AccountingPeriod", "Period")
                        .WithMany("AccrualEntries")
                        .HasForeignKey("PeriodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_accrual_entries_accounting_periods_period_id");

                    b.HasOne("Fintech.Core.Domain.JournalEntry", "ReversalJournalEntry")
                        .WithMany()
                        .HasForeignKey("ReversalJournalEntryId")
                        .HasConstraintName("fk_accrual_entries_journal_entries_reversal_journal_entry_id");

                    b.Navigation("JournalEntry");

                    b.Navigation("Loan");

                    b.Navigation("Period");

                    b.Navigation("ReversalJournalEntry");
                });

            modelBuilder.Entity("Fintech.Core.Domain.CapitalAccount", b =>
                {
                    b.HasOne("Fintech.Core.Domain.Partner", "Partner")
                        .WithMany("CapitalAccounts")
                        .HasForeignKey("PartnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_capital_accounts_partners_partner_id");

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("Fintech.Core.Domain.CapitalAccountHistory", b =>
                {
                    b.HasOne("Fintech.Core.Domain.CapitalAccount", "CapitalAccount")
                        .WithMany("History")
                        .HasForeignKey("CapitalAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_capital_account_histories_capital_accounts_capital_account_");

                    b.Navigation("CapitalAccount");
                });

            modelBuilder.Entity("Fintech.Core.Domain.CapitalTransaction", b =>
                {
                    b.HasOne("Fintech.Core.Domain.User", "ApprovedByUser")
                        .WithMany()
                        .HasForeignKey("ApprovedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_capital_transactions_users_approved_by");

                    b.HasOne("Fintech.Core.Domain.CapitalAccount", "CapitalAccount")
                        .WithMany("Transactions")
                        .HasForeignKey("CapitalAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_capital_transactions_capital_accounts_capital_account_id");

                    b.HasOne("Fintech.Core.Domain.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_capital_transactions_users_created_by");

                    b.Navigation("ApprovedByUser");

                    b.Navigation("CapitalAccount");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("Fintech.Core.Domain.CollectionRequest", b =>
                {
                    b.HasOne("Fintech.Core.Domain.User", "ApprovedBy")
                        .WithMany()
                        .HasForeignKey("ApprovedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_collection_requests_users_approved_by_id");

                    b.HasOne("Fintech.Core.Domain.Installment", "Installment")
                        .WithMany()
                        .HasForeignKey("InstallmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_collection_requests_installments_installment_id");

                    b.HasOne("Fintech.Core.Domain.LoanCase", "LoanCase")
                        .WithMany()
                        .HasForeignKey("LoanCaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_collection_requests_loan_cases_loan_case_id");

                    b.HasOne("Fintech.Core.Domain.User", "RequestedBy")
                        .WithMany()
                        .HasForeignKey("RequestedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_collection_requests_users_requested_by_id");

                    b.Navigation("ApprovedBy");

                    b.Navigation("Installment");

                    b.Navigation("LoanCase");

                    b.Navigation("RequestedBy");
                });

            modelBuilder.Entity("Fintech.Core.Domain.Installment", b =>
                {
                    b.HasOne("Fintech.Core.Domain.LoanCase", "LoanCase")
                        .WithMany("Installments")
                        .HasForeignKey("LoanCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_installments_loan_cases_loan_case_id");

                    b.Navigation("LoanCase");
                });

            modelBuilder.Entity("Fintech.Core.Domain.JournalEntry", b =>
                {
                    b.HasOne("Fintech.Core.Domain.CapitalTransaction", null)
                        .WithMany("JournalEntries")
                        .HasForeignKey("CapitalTransactionId")
                        .HasConstraintName("fk_journal_entries_capital_transactions_capital_transaction_id");
                });

            modelBuilder.Entity("Fintech.Core.Domain.JournalLine", b =>
                {
                    b.HasOne("Fintech.Core.Domain.JournalEntry", "JournalEntry")
                        .WithMany("Lines")
                        .HasForeignKey("JournalEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_journal_lines_journal_entries_journal_entry_id");

                    b.Navigation("JournalEntry");
                });

            modelBuilder.Entity("Fintech.Core.Domain.LoanCase", b =>
                {
                    b.HasOne("Fintech.Core.Domain.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_loan_cases_customers_customer_id");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Fintech.Core.Domain.Partner", b =>
                {
                    b.HasOne("Fintech.Core.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_partners_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Fintech.Core.Domain.PeriodReversal", b =>
                {
                    b.HasOne("Fintech.Core.Domain.AccountingPeriod", "Period")
                        .WithMany("Reversals")
                        .HasForeignKey("PeriodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_period_reversals_accounting_periods_period_id");

                    b.Navigation("Period");
                });

            modelBuilder.Entity("Fintech.Core.Domain.ProfitDistribution", b =>
                {
                    b.HasOne("Fintech.Core.Domain.Partner", "Partner")
                        .WithMany()
                        .HasForeignKey("PartnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_profit_distributions_partners_partner_id");

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("Fintech.Core.Domain.ProvisionEntry", b =>
                {
                    b.HasOne("Fintech.Core.Domain.JournalEntry", "JournalEntry")
                        .WithMany()
                        .HasForeignKey("JournalEntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_provision_entries_journal_entries_journal_entry_id");

                    b.HasOne("Fintech.Core.Domain.LoanCase", "Loan")
                        .WithMany()
                        .HasForeignKey("LoanId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_provision_entries_loan_cases_loan_id");

                    b.HasOne("Fintech.Core.Domain.AccountingPeriod", "Period")
                        .WithMany("ProvisionEntries")
                        .HasForeignKey("PeriodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_provision_entries_accounting_periods_period_id");

                    b.Navigation("JournalEntry");

                    b.Navigation("Loan");

                    b.Navigation("Period");
                });

            modelBuilder.Entity("Fintech.Core.Domain.Receipt", b =>
                {
                    b.HasOne("Fintech.Core.Domain.Installment", "Installment")
                        .WithMany()
                        .HasForeignKey("InstallmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_receipts_installments_installment_id");

                    b.HasOne("Fintech.Core.Domain.LoanCase", "LoanCase")
                        .WithMany()
                        .HasForeignKey("LoanCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_receipts_loan_cases_loan_case_id");

                    b.Navigation("Installment");

                    b.Navigation("LoanCase");
                });

            modelBuilder.Entity("Fintech.Core.Domain.AccountingPeriod", b =>
                {
                    b.Navigation("AccrualEntries");

                    b.Navigation("ProvisionEntries");

                    b.Navigation("Reversals");
                });

            modelBuilder.Entity("Fintech.Core.Domain.CapitalAccount", b =>
                {
                    b.Navigation("History");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Fintech.Core.Domain.CapitalTransaction", b =>
                {
                    b.Navigation("JournalEntries");
                });

            modelBuilder.Entity("Fintech.Core.Domain.JournalEntry", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Fintech.Core.Domain.LoanCase", b =>
                {
                    b.Navigation("Installments");
                });

            modelBuilder.Entity("Fintech.Core.Domain.Partner", b =>
                {
                    b.Navigation("CapitalAccounts");
                });
#pragma warning restore 612, 618
        }
    }
}
